# action.yml
name: 'Alexa ASK AWS CLI Action'
author: 'Xavier Portilla Edo'
description: 'Github Action using Docker image for ASK and AWS CLI '
branding:
  icon: 'activity'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
