# action.yml
name: 'Alexa ASK AWS CLI Action'
author: 'Xavier Portilla Edo'
description: 'Github Action using Docker image for ASK and AWS CLI '
branding:
  icon: 'activity'  
  color: 'blue'
inputs:
  exec:  # id of input
    description: 'Command to execute'
    required: true
    default: 'ask --version'
outputs:
  result: # id of output
    description: 'The result of the command'
runs:
  using: 'docker'
  image: './.github/action/Dockerfile'
